version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      # Uncomment the database you want to use
      # - DATABASE_URL=mysql://user:password@mysql:3306/dbname
      # - DATABASE_URL=postgresql://user:password@postgres:5432/dbname
    depends_on:
      - redis
      # Uncomment the database you want to use
      # - mysql
      # - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Uncomment the database you want to use
  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=dbname
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=dbname
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  # Uncomment the volume you want to use
  # mysql_data:
  # postgres_data: 